### ISSUE TITLE
go get neilpa.me/yajsv is failing 

### ISSUE THREAD

**Issue by umakarnati** [neilpa/yajsv#19]
go get neilpa.me/yajsv setup command is failing with below error

```


 go get neilpa.me/yajsv
  shell: /usr/bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.16.6/x64
go: downloading neilpa.me/yajsv v1.4.0
go get: neilpa.me/yajsv@none updating to
	neilpa.me/yajsv@v1.4.0: parsing go.mod:
	**module declares its path as: github.com/neilpa/yajsv**
	        but was required as: neilpa.me/yajsv
**Error: Process completed with exit code 1.**
```

using command **`go get github.com/neilpa/yajsv`**   instead of **`go get neilpa.me/yajsv`**   worked fine .. it seems README document needs to updated with correct command

**Comment by neilpa** [comment]
Thanks for the heads up. I'm just using github pages and custom domains to host this so I suspect something may have broken on their end. If I curl for `neilpa.me/yajsv` it no longer returns the [custom page](https://github.com/neilpa/neilpa.github.io/blob/master/yajsv.html) I added which includes the metadata that `go get`, etc. depends on to resolve the import.

```
$ curl -i neilpa.me/yajsv     
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: https://neilpa.me/yajsv
X-GitHub-Request-Id: 4CF6:7850:2D13A:A7BFE:61A5BA9D
Content-Length: 162
Accept-Ranges: bytes
Date: Tue, 30 Nov 2021 05:54:26 GMT
Via: 1.1 varnish
Age: 500
Connection: keep-alive
X-Served-By: cache-sea4476-SEA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1638251666.240287,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: ff3dc1fccca629617afa5da75d285e006e20f0d9

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Maybe github is trying to do something "smart" with the `<meta http-equiv="refresh" ... />` and caching that breaks this scenario since it now 301s to the repo page. I'll have to dig a bit more into this or maybe put up a dummy page that avoids the redirect.

**Comment by neilpa** [comment]
I submitted a ticket to GH support to see what they say.
